/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_insert_bytes.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3cb0d3d01b580eab0625b2cf8dcc8678)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/pdu_insert_bytes.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_insert_bytes_pydoc.h>

void bind_pdu_insert_bytes(py::module& m)
{

    using pdu_insert_bytes = ::gr::satellites::pdu_insert_bytes;


    py::class_<pdu_insert_bytes,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_insert_bytes>>(
        m, "pdu_insert_bytes", D(pdu_insert_bytes))

        .def(py::init(&pdu_insert_bytes::make),
             py::arg("pos"),
             py::arg("bytes"),
             D(pdu_insert_bytes, make))


        ;
}
